# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-06 03:15
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('circles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CircleBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '圈子搜索',
                'verbose_name_plural': '圈子搜索',
            },
        ),
        migrations.CreateModel(
            name='CircleHotSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField(default='', help_text='关键字', max_length=20, verbose_name='关键字')),
                ('count', models.IntegerField(blank=True, default=0, help_text='搜索次数', null=True, verbose_name='搜索次数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '圈子搜索',
                'verbose_name_plural': '圈子搜索',
            },
        ),
        migrations.RemoveField(
            model_name='circle',
            name='created',
        ),
        migrations.AddField(
            model_name='circle',
            name='user',
            field=models.ForeignKey(default=1, help_text='创建人', max_length=20, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='circlepartnermessage',
            name='type',
            field=models.IntegerField(default=0, help_text='消息类型', verbose_name='消息类型'),
        ),
        migrations.AddField(
            model_name='circlepartnermessage',
            name='user_image_url',
            field=models.TextField(default='', verbose_name='用户头像'),
        ),
        migrations.AlterField(
            model_name='circle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='circleimage', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='circlepartnermessage',
            name='circle',
            field=models.ForeignKey(help_text='所属圈子', on_delete=django.db.models.deletion.CASCADE, related_name='circle', to='circles.Circle', verbose_name='所属圈子'),
        ),
        migrations.AlterField(
            model_name='circlepartnermessage',
            name='message',
            field=models.TextField(default='', help_text='聊天信息', verbose_name='聊天消息'),
        ),
        migrations.AddField(
            model_name='circlebanner',
            name='circle',
            field=models.ForeignKey(help_text='所属圈子', on_delete=django.db.models.deletion.CASCADE, to='circles.Circle', verbose_name='所属圈子'),
        ),
    ]
