# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-09 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0002_auto_20180206_0315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='circlebanner',
            options={'verbose_name': '圈子轮播', 'verbose_name_plural': '圈子轮播'},
        ),
        migrations.AddField(
            model_name='circle',
            name='watch_num',
            field=models.IntegerField(default=0, help_text='围观次数', verbose_name='围观次数'),
        ),
    ]
