# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-30 10:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('circles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', help_text='发布人', max_length=20, verbose_name='发布人')),
                ('end_time', models.DateTimeField(default=datetime.datetime.now, help_text='结束时间', verbose_name='结束时间')),
                ('content', models.CharField(default='', help_text='计划详情', max_length=200, verbose_name='计划详情')),
                ('address', models.CharField(default='', help_text='地点', max_length=50, verbose_name='地点')),
                ('users_num', models.IntegerField(default=0, help_text='参与人数', verbose_name='参与人数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('from_circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_list', to='circles.Circle', verbose_name='来源圈子')),
            ],
            options={
                'verbose_name': '计划',
                'verbose_name_plural': '计划',
            },
        ),
    ]
